In [1]:
import numpy as np

In [5]:
arr = np.array([10,20,30,40,50])
print (arr)

[10 20 30 40 50]


In [7]:
arr1 = np.array([[1,2],[3,4]])
print (arr1)

[[1 2]
 [3 4]]


In [19]:
arr2 = np.eye((4) , dtype = "int64")
print(arr2)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [20]:
arr3 = np.full((4,4),7, dtype = "int64")
print(arr3)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [21]:
arr4 = np.ones((3,3), dtype = "int32")
print(arr4)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [29]:
arr5 = np.arange(0,9,2)
print(arr5)

[0 2 4 6 8]


In [34]:
arr6 = np.linspace(0,1,6)
print(arr6)

[0.  0.2 0.4 0.6 0.8 1. ]


In [48]:
arr7 = np.arange(1,10)
print(arr7)
arr8 = arr7.reshape(3,3)
print(arr8)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [49]:
arr9 =np.arange(1,10).reshape(3,3)
print(arr9)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [53]:
arr10 = np.linspace(10,50,5)
print(arr10)

[10. 20. 30. 40. 50.]


In [63]:
arr11 = np.arange(24)
print(arr11)
print(arr11.ndim)
print(arr11.size)
print(arr11.dtype)
print(arr11.shape)
print(arr11.itemsize)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1
24
int64
(24,)
8


In [66]:
arr12 = np.arange(1,28).reshape(3,3,3)
print(arr12)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [89]:
arr = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])
print(arr[:,2])

[30 60 90]


In [7]:
import numpy as np


In [9]:
arr1 = np.arange(5,31,5).reshape(2,3)
print(arr1)

[[ 5 10 15]
 [20 25 30]]


In [14]:
arr = np.arange(1,10)
view_arr = arr[1:8]
view_arr[2] = 333
print (view_arr)
print(arr)

[  2   3 333   5   6   7   8]
[  1   2   3 333   5   6   7   8   9]


In [16]:
py_arr = [1,2,3,4,5]
copy_arr = py_arr[1:4]
copy_arr[2] = 500
print(copy_arr)
print(py_arr)

[2, 3, 500]
[1, 2, 3, 4, 5]


In [22]:
arr = np.array([1, 2, 3])
print(arr.dtype)
print(arr.ndim)
print(arr.shape)
float_type = arr.astype("float64")
print (float_type,float_type.dtype)

int64
1
(3,)
[1. 2. 3.] float64


In [23]:
arr = np.array([1.5, 2.8, 3.9, 4.2])
narr = arr.astype("int64")
print(narr,narr.dtype)

[1 2 3 4] int64


In [29]:
arr = np.arange(24).reshape(2, 3, 4)
print(arr[][1][2])

[20 21 22 23]
