# ====================================================
# NumPy Final Challenge
# ====================================================

# Create the following array:
# arr = np.arange(1, 26).reshape(5,5)

# Tasks:
# 1. Print the shape.
# 2. Print the third row.
# 3. Print the second column.
# 4. Print the bottom-right 2×2 matrix.
# 5. Replace 13 with 1300.
# 6. Convert the array to float64.
# 7. Find the sum of every row.
# 8. Find the maximum value of every column.
# 9. Print only even numbers using boolean indexing.
# 10. Flatten the array into a 1D array.

In [5]:
import numpy as np
arr = np.arange(1,26).reshape(5,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [7]:
# 1. Print the shape.
print(arr.shape)

(5, 5)


In [8]:
# 2. Print the third row.
print(arr[2,:])

[11 12 13 14 15]


In [10]:
# 3. Print the second column.
print(arr[:,1])

[ 2  7 12 17 22]


In [11]:
# 4. Print the bottom-right 2×2 matrix.
print(arr[3:,3:])

[[19 20]
 [24 25]]


In [17]:
# 5. Replace 13 with 1300.
arr[2,2] = 1300
print(arr)

[[   1    2    3    4    5]
 [   6    7    8    9   10]
 [  11   12 1300   14   15]
 [  16   17   18   19   20]
 [  21   22   23   24   25]]


In [27]:
# 6. Convert the array to float64.
arr1 = arr.astype(np.float16)
print(arr1)

[[1.0e+00 2.0e+00 3.0e+00 4.0e+00 5.0e+00]
 [6.0e+00 7.0e+00 8.0e+00 9.0e+00 1.0e+01]
 [1.1e+01 1.2e+01 1.3e+03 1.4e+01 1.5e+01]
 [1.6e+01 1.7e+01 1.8e+01 1.9e+01 2.0e+01]
 [2.1e+01 2.2e+01 2.3e+01 2.4e+01 2.5e+01]]


In [43]:
# 7. Find the sum of every row.
row1 = np.sum(arr,axis = 1)
print(row1)

[  15   40 1352   90  115]


In [45]:
# 8. Find the maximum value of every column.
max_col = np.max(arr,axis =0)
print(max_col)

[  21   22 1300   24   25]


In [46]:
# 9. Print only even numbers using boolean indexing.
print(arr[arr%2 == 0])

[   2    4    6    8   10   12 1300   14   16   18   20   22   24]


In [47]:
# 10. Flatten the array into a 1D array.

In [49]:
print(arr.flatten())

[   1    2    3    4    5    6    7    8    9   10   11   12 1300   14
   15   16   17   18   19   20   21   22   23   24   25]
